import Head from 'next/head'
import Image from 'next/image'
import colors from 'tailwindcss/colors'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Find New Dishes <span className="block text-indigo-500 xl:inline">On the Fly!</span>
        </h1>
        <p className="mt-3 max-w-md items-center text-base text-gray-500 sm:text-lg sm:justify-center md:mt-5 md:text-xl md:max-w-3xl">
        Having trouble deciding where to eat or what to cook? Our easy to use application will help you
        figure out a place to eat from a single swipe, help you find awesome recipes, 
        and help you track your food habits and nutrition! {' '} 
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Browse Recipes &rarr;</h2>
            <p>Cooking is a staple. Discover new recipes to expand your culinary horizons.</p>
          </a>

          <a href="#" className={styles.card}>
            <h2><span className="block text-indigo-500 xl:inline">Browse Restaurants &rarr;</span></h2>
            <p><span className="block text-indigo-500 xl:inline">In a rush with little time to cook? Find new restaurants around you.</span></p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
